/**
 * Sample values for previewing platform email.
 *
 * Never real customer data — these appear in the admin preview and in test
 * sends, both of which can be shown on a shared screen.
 */
export const PLATFORM_EXAMPLE_VARIABLES: Record<string, string> = {
  brand: "Loopinglive",
  host_name: "Chinedu",
  name: "Sarah",
  member_name: "Ade",
  inviter_name: "Chinedu Mendel",
  registrant_name: "Sarah Okonkwo",
  buyer_name: "Sarah Okonkwo",
  support_email: "support@loopinglive.com",

  webinar_title: "The 3-Offer Framework",
  offer_title: "The Complete Sales System",
  workspace_name: "Mendel Media",
  role_name: "Editor",
  previous_role: "Viewer",

  video_name: "3-offer-framework-final.mp4",
  video_duration: "48 minutes",
  failure_reason: "The file could not be decoded",

  session_time: "Thursday 4 September, 8:00 PM",
  old_session_time: "Wednesday 3 September, 8:00 PM",
  next_session: "Friday 5 September, 8:00 PM",
  next_session_note: "The next session runs Friday 5 September at 8:00 PM.",

  event_time: "3 September 2026, 09:14 BST",
  event_location: "London, United Kingdom",
  device: "Chrome on Windows",
  expires_in: "24 hours",

  registered_count: "42",
  attended_count: "27",
  clicked_count: "9",
  bought_count: "6",
  registrations_count: "128",
  avg_watch: "63%",
  revenue: "$5,982",
  biggest_drop: "18:40",
  top_webinar: "The 3-Offer Framework",
  top_conversion: "22%",
  milestone: "100",

  steps_remaining: "3 steps",
  steps_list: "- Fake personas\n- Offer button\n- AI moderators",
  steps_done: "4",
  steps_total: "7",

  amount: "$347",
  plan_name: "Yearly",
  previous_plan: "Monthly",
  plan_price: "$347 per year",
  trial_days: "14",
  trial_end_date: "17 September 2026",
  period_start: "3 September 2026",
  period_end: "3 September 2027",
  next_payment_date: "3 September 2027",
  invoice_number: "LL-2026-0417",
  retry_date: "6 September 2026",
  final_date: "10 September 2026",
  effective_date: "3 September 2026",
  access_until: "3 September 2027",
  proration_note: "The difference has been credited to your next invoice.",
  card_last4: "4242",
  card_expiry: "10/2026",
  usage_current: "820",
  usage_limit: "1,000",
  usage_unit: "registrations",
  days_remaining: "11",
  reset_date: "1 October 2026",

  bounce_count: "3",
  bounce_reason: "Recipient address does not exist",
  sending_domain: "loopinglive.com",
  deleted_summary: "2 webinars, 1,284 registrants and all associated analytics",
  sessions_count: "6",

  purchase_date: "3 September 2026",
  refund_days: "5 to 10 working days",
  replay_expires_at: "Saturday 6 September, 8:00 PM",
  offer_closes_at: "Friday at midnight",
  waitlist_position: "4th",
  resubscribe_note: "Register again and you will start receiving them.",

  dashboard_url: "https://loopinglive.com/dashboard",
  webinar_url: "https://loopinglive.com/admin/webinar/demo",
  registration_url: "https://loopinglive.com/webinar/demo/register",
  webinar_link: "https://loopinglive.com/webinar/demo/register",
  attendees_url: "https://loopinglive.com/admin/webinar/demo/attendees",
  analytics_url: "https://loopinglive.com/admin/webinar/demo/analytics",
  comments_url: "https://loopinglive.com/admin/webinar/demo/comments",
  live_url: "https://loopinglive.com/admin/live",
  billing_url: "https://loopinglive.com/settings/billing",
  security_url: "https://loopinglive.com/settings",
  team_url: "https://loopinglive.com/settings/team",
  invoice_url: "https://loopinglive.com/invoice/LL-2026-0417",
  action_url: "https://loopinglive.com/auth/action?token=example",
  access_url: "https://loopinglive.com/offer/demo",
  feedback_url: "https://loopinglive.com/feedback/example",
  offer_url: "https://loopinglive.com/offer/demo",
  replay_link: "https://loopinglive.com/replay/example",

  unsubscribe_link: "https://loopinglive.com/api/automation/unsubscribe?e=example",
};
