import type { Metadata } from "next";

import { LegalPage, type LegalSection } from "@/components/marketing/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "What data Loopinglive collects, why, who it is shared with, and the rights you have over it.",
};

const UPDATED = "3 September 2026";

const SECTIONS: LegalSection[] = [
  {
    id: "roles",
    heading: "Two kinds of people, two different roles",
    body: (
      <>
        <p>
          This matters for what rights apply, so it comes first.
        </p>
        <p>
          <strong>Hosts</strong> are our customers. For their data we are the
          controller — we decide what to collect and why.
        </p>
        <p>
          <strong>Attendees</strong> register for a host&rsquo;s webinar. For their
          data the host is the controller and we are the processor: we hold and
          process it on that host&rsquo;s instructions. If you attended a webinar and
          want your data removed, the fastest route is the host who ran it, though you
          can also contact us.
        </p>
      </>
    ),
  },
  {
    id: "collected",
    heading: "What we collect",
    body: (
      <>
        <p>
          <strong>From hosts:</strong> name, email, password (hashed, never stored in
          readable form), and billing details. Card numbers go directly to Stripe and
          never touch our servers — we store only the last four digits and expiry that
          Stripe returns.
        </p>
        <p>
          <strong>From attendees:</strong> name, email, phone number and country, plus
          what happened in the session — whether they joined, how much they watched,
          whether they clicked the offer, and their chat messages.
        </p>
        <p>
          <strong>Automatically:</strong> device type, browser, operating system, and
          the country your IP address resolves to. We store the country, not the IP
          address itself. We also record which link brought someone to a registration
          page.
        </p>
        <p>
          <strong>Errors:</strong> when something breaks we log the message, the page,
          and the browser, so we can fix it.
        </p>
      </>
    ),
  },
  {
    id: "why",
    heading: "Why we use it",
    body: (
      <ul>
        <li>To run the service — playing webinars, showing chat, tracking attendance.</li>
        <li>To send the reminders and follow-ups a host has configured.</li>
        <li>To give hosts analytics about their own webinars.</li>
        <li>To take payment and prevent fraud.</li>
        <li>To support you when you ask, and to fix faults.</li>
      </ul>
    ),
  },
  {
    id: "ai",
    heading: "AI-generated replies",
    body: (
      <>
        <p>
          Some chat replies are generated by AI. When that happens, the message being
          replied to and the webinar&rsquo;s context are sent to Anthropic&rsquo;s API
          to produce the reply.
        </p>
        <p>
          We do not send attendee email addresses or phone numbers for this. Anthropic
          does not train its models on data submitted through its API.
        </p>
      </>
    ),
  },
  {
    id: "sharing",
    heading: "Who else sees it",
    body: (
      <>
        <p>We use these providers, each for one job:</p>
        <ul>
          <li>
            <strong>Supabase</strong> — database and authentication.
          </li>
          <li>
            <strong>Vercel</strong> — hosting.
          </li>
          <li>
            <strong>Cloudinary</strong> — video storage and delivery.
          </li>
          <li>
            <strong>Stripe</strong> — payments. They receive billing data directly.
          </li>
          <li>
            <strong>Resend</strong> — email delivery.
          </li>
          <li>
            <strong>Twilio</strong> — SMS and WhatsApp, where a host enables them.
          </li>
          <li>
            <strong>Anthropic</strong> — AI chat replies, as described above.
          </li>
        </ul>
        <p>
          If a host connects their own tools, their attendee data is also sent there
          at that host&rsquo;s instruction.
        </p>
        <p>
          <strong>We do not sell personal data.</strong> Some of these providers are
          outside the UK and EEA; transfers rely on standard contractual clauses or an
          adequacy decision.
        </p>
      </>
    ),
  },
  {
    id: "retention",
    heading: "How long we keep it",
    body: (
      <ul>
        <li>Host accounts: while the account is open, then 30 days after closure.</li>
        <li>
          Attendee records: while the host&rsquo;s account is open, or until the host
          deletes them.
        </li>
        <li>Message and delivery logs: 12 months.</li>
        <li>Error logs: 90 days.</li>
        <li>Invoices: 7 years, because tax law requires it.</li>
      </ul>
    ),
  },
  {
    id: "rights",
    heading: "Your rights",
    body: (
      <>
        <p>Under UK and EU data protection law you can ask to:</p>
        <ul>
          <li>See what we hold about you.</li>
          <li>Correct anything wrong.</li>
          <li>Have it deleted.</li>
          <li>Receive it in a portable format.</li>
          <li>Object to or restrict how it is used.</li>
          <li>Withdraw consent, including by unsubscribing from any message.</li>
        </ul>
        <p>
          Email <a href="mailto:support@loopinglive.com">support@loopinglive.com</a>{" "}
          and we will respond within 30 days. You can also complain to the ICO
          (ico.org.uk) or your local supervisory authority.
        </p>
      </>
    ),
  },
  {
    id: "cookies",
    heading: "Cookies",
    body: (
      <>
        <p>We use as few as we can get away with:</p>
        <ul>
          <li>
            <strong>Essential:</strong> your login session, and the impersonation flag
            used by our support staff. The site does not work without these.
          </li>
          <li>
            <strong>Referral:</strong> if you arrive through an affiliate link we
            store that code for 30 days so the referrer is credited.
          </li>
        </ul>
        <p>
          We set no advertising or cross-site tracking cookies. A host may add their
          own analytics or pixel to their registration page — that is their choice and
          their disclosure to make.
        </p>
      </>
    ),
  },
  {
    id: "security",
    heading: "Security",
    body: (
      <>
        <p>
          Everything is served over HTTPS. Passwords are hashed. API keys are stored
          as hashes, so a leak of our database does not expose usable keys. Database
          access is restricted by row-level security so one account cannot read
          another&rsquo;s data.
        </p>
        <p>
          No system is perfectly secure. If a breach affects you we will tell you and
          the regulator within 72 hours of becoming aware.
        </p>
      </>
    ),
  },
  {
    id: "children",
    heading: "Children",
    body: (
      <p>
        Loopinglive is not for under-18s and we do not knowingly collect their data.
        Tell us if you believe we have, and we will delete it.
      </p>
    ),
  },
  {
    id: "contact",
    heading: "Contact",
    body: (
      <p>
        Email <a href="mailto:support@loopinglive.com">support@loopinglive.com</a> for
        anything in this policy, including data requests.
      </p>
    ),
  },
];

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      updated={UPDATED}
      intro={
        <p>
          What we collect, why, who else sees it, and what you can ask us to do about
          it. Written to be understood rather than to cover us.
        </p>
      }
      sections={SECTIONS}
    />
  );
}
