/**
 * AI insights — rule-based synthesis, no database access and no model call.
 *
 * "AI insights" in this feature means insights *about* the account's real
 * numbers, generated by named, inspectable thresholds — not a language model
 * asked to look at a dashboard and invent commentary. A host reading "your
 * conversion rate dropped 40%" needs that to be a fact, not a plausible
 *-sounding guess.
 */

export type InsightCandidate = {
  insightType: string;
  title: string;
  body: string;
  actionItems: string[];
  priority: "low" | "medium" | "high";
};

export type FunnelComparison = {
  currentRegistrants: number;
  previousRegistrants: number;
  currentAttendanceRate: number;
  previousAttendanceRate: number;
  currentConversionRate: number;
  previousConversionRate: number;
};

const MIN_SAMPLE = 5;

function relativeChange(current: number, previous: number): number | null {
  if (previous === 0) return null;
  return ((current - previous) / previous) * 100;
}

export function funnelInsights(funnel: FunnelComparison): InsightCandidate[] {
  const insights: InsightCandidate[] = [];

  if (funnel.previousRegistrants >= MIN_SAMPLE) {
    const registrantChange = relativeChange(funnel.currentRegistrants, funnel.previousRegistrants);
    if (registrantChange !== null && registrantChange <= -25) {
      insights.push({
        insightType: "registrant_volume_drop",
        title: "Registrations dropped this week",
        body: `${funnel.currentRegistrants} registrants this week, down ${Math.abs(Math.round(registrantChange))}% from ${funnel.previousRegistrants} the week before.`,
        actionItems: ["Check whether traffic sources or ad spend changed", "Review the registration page for anything broken"],
        priority: "medium",
      });
    }
  }

  const attendanceDelta = funnel.currentAttendanceRate - funnel.previousAttendanceRate;
  if (funnel.previousRegistrants >= MIN_SAMPLE) {
    if (attendanceDelta <= -15) {
      insights.push({
        insightType: "attendance_rate_drop",
        title: "Show-up rate is falling",
        body: `${funnel.currentAttendanceRate}% attended this week, down from ${funnel.previousAttendanceRate}% the week before.`,
        actionItems: ["Review reminder email and SMS timing", "Check the confirmation message is setting the right expectation"],
        priority: "high",
      });
    } else if (attendanceDelta >= 15) {
      insights.push({
        insightType: "attendance_rate_up",
        title: "Show-up rate is climbing",
        body: `${funnel.currentAttendanceRate}% attended this week, up from ${funnel.previousAttendanceRate}% the week before.`,
        actionItems: ["Whatever changed recently, keep doing it"],
        priority: "low",
      });
    }
  }

  if (funnel.previousConversionRate > 0 && funnel.currentRegistrants >= MIN_SAMPLE) {
    const conversionChange = relativeChange(funnel.currentConversionRate, funnel.previousConversionRate);
    if (conversionChange !== null && conversionChange <= -30) {
      insights.push({
        insightType: "conversion_rate_drop",
        title: "Conversion rate dropped",
        body: `${funnel.currentConversionRate}% of attendees bought this week, down from ${funnel.previousConversionRate}% the week before.`,
        actionItems: ["Review the offer pitch and pricing", "Check the offer button is showing at the right time in the video"],
        priority: "high",
      });
    }
  }

  return insights;
}

export function hotLeadsInsight(hotLeadCount: number): InsightCandidate | null {
  if (hotLeadCount < 5) return null;
  return {
    insightType: "hot_leads_ready",
    title: `${hotLeadCount} hot leads ready to follow up`,
    body: `${hotLeadCount} attendees scored 80+ on engagement and haven't bought yet.`,
    actionItems: ["Send a personal follow-up to your highest scorers", "Consider a limited-time reminder of the offer"],
    priority: "medium",
  };
}

export function abTestWinnerInsight(input: {
  testName: string;
  winner: "a" | "b";
  confidenceLevel: number;
}): InsightCandidate {
  return {
    insightType: "ab_test_winner",
    title: `"${input.testName}" has a clear winner`,
    body: `Variant ${input.winner.toUpperCase()} is ahead with ${input.confidenceLevel}% confidence.`,
    actionItems: ["Apply the winning variant", "Start your next test"],
    priority: "medium",
  };
}

export function scheduleRecommendationInsight(input: {
  dayLabel: string;
  hourLabel: string;
  attendanceRate: number | null;
  confidenceScore: number;
}): InsightCandidate | null {
  if (input.confidenceScore < 60) return null;
  return {
    insightType: "schedule_recommendation",
    title: "A better time slot is available",
    body:
      input.attendanceRate !== null
        ? `${input.dayLabel} at ${input.hourLabel} has historically converted ${input.attendanceRate}% of registrants into attendees for this webinar.`
        : `${input.dayLabel} at ${input.hourLabel} is a strong slot based on general industry patterns.`,
    actionItems: ["Schedule your next session for this slot"],
    priority: "low",
  };
}
